name: 'Setup Package Version'
description: 'Sets up package version with beta tag and auto-incremented index'

runs:
    using: 'composite'
    steps:
      - name: Setup core version
        shell: bash
        run: |
            CORE_VERSION=$(npm pkg get dependencies.@wocker/core | sed -e 's/^"//' -e 's/"$//')
            CORE_BETA_VERSION=$(npm view @wocker/core@beta version 2> /dev/null || echo "")
            if [[ "$CORE_BETA_VERSION" == "$CORE_VERSION"* ]]; then
                npm pkg set "dependencies.@wocker/core=^$CORE_BETA_VERSION"
                npm pkg set "overrides.@wocker/testing.@wocker/core=^$CORE_BETA_VERSION"
            fi

      - name: Setup testing version
        shell: bash
        run: |
            TESTING_VERSION=$(npm pkg get devDependencies.@wocker/testing | sed -e 's/^"//' -e 's/"$//')
            TESTING_BETA_VERSION=$(npm view @wocker/testing@beta version 2> /dev/null || echo "")
            if [[ "$TESTING_BETA_VERSION" == "$TESTING_VERSION"* ]]; then
                npm pkg set "devDependencies.@wocker/testing=^$TESTING_BETA_VERSION"
            fi

      - name: Setup version
        shell: bash
        run: |
            PACKAGE_NAME=$(npm pkg get name | sed -e 's/^"//' -e 's/"$//')
            PACKAGE_VERSION=$(npm pkg get version | sed -e 's/^"//' -e 's/"$//')
            BETA_VERSION=$(npm view $PACKAGE_NAME@beta version 2>/dev/null || echo "")
            if [[ "$BETA_VERSION" == "$PACKAGE_VERSION"* ]]; then
                INDEX=$(echo $BETA_VERSION | sed -r -e 's/^[0-9]+\.[0-9]+\.[0-9]+-beta\.//' | awk '{print $0+1}')
            else
                INDEX=0
            fi
            npm pkg set version=$PACKAGE_VERSION-beta.$INDEX
