name: Test

on:
    pull_request:
        paths:
            - src
            - package.json
            - tsconfig.json
        types:
            - opened
            - reopened
            - synchronize

jobs:
    test:
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20
                registry-url: 'https://registry.npmjs.org'

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                restore-keys: |
                  ${{ runner.os }}-npm-

            - name: Install dependencies
              run: npm install

    publish:
        needs: test
        runs-on: ubuntu-latest
        environment: publish
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
                node-version: 20
                registry-url: 'https://registry.npmjs.org'

          - name: Cache dependencies
            uses: actions/cache@v3
            with:
                path: ~/.npm
                key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
                restore-keys: |
                  ${{ runner.os }}-npm-

          - name: Setup version
            run: |
                PACKAGE_NAME=$(npm pkg get name | sed -e 's/^"//' -e 's/"$//')
                PACKAGE_VERSION=$(npm pkg get version | sed -e 's/^"//' -e 's/"$//')
                PUBLISHED_VERSION=$(npm view $PACKAGE_NAME@dev version 2>/dev/null || echo "")
                if [[ "$PUBLISHED_VERSION" == "$PACKAGE_VERSION"* ]]; then
                    INDEX=$(echo $PUBLISHED_VERSION | sed -r -e 's/^[0-9]+\.[0-9]+\.[0-9]+-dev\.//' | awk '{print $0+1}')
                else
                    INDEX=0
                fi
                npm pkg set version=$PACKAGE_VERSION-dev.$INDEX
                CORE_VERSION=$(npm pkg get dependencies.@wocker/core | sed -e 's/^"//' -e 's/"$//')
                CORE_DEV_VERSION=$(npm view @wocker/core@dev version 2> /dev/null || echo "")
                if [[ "$CORE_DEV_VERSION" == "$CORE_VERSION"* ]]; then
                    npm pkg set "dependencies.@wocker/core=$CORE_DEV_VERSION"
                fi

          - name: Install dependencies
            run: npm install

          - name: Build
            run: npm run build

          - name: Publish to NPM
            env:
                NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
            run: |
                npm publish --tag dev
